name: CICD Database Dev to Prod  

on:
  push:
    branches:
      - main

jobs:
  db_cicd:
    name: Database CI/CD
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4 #Checkout ke repository yang digunakan
      - name: SSH Connect
        uses: appleboy/scp-action@v1 #Digunakan untuk konek ke server melaui SSH
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            echo "Berhasil konek ke server"